# Caching is not supported yet, even though Azure supports it. The only
# problem, for whatever reason Rust does not use the cached target/ directory
# and compiles everything anyway. Also, downloading the 1GB cache takes a good
# minute by itself so it's not that important.

trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - template: continuous-integration/install-binaryen.yaml
      - template: continuous-integration/install-wasmbindgen.yaml
      - template: continuous-integration/install-wasmpack.yaml
      - script: ./build.sh
        displayName: Build
    - job: Format
      steps:
      - script: rustup component add rustfmt
        displayName: Install Rustfmt
      - script: cargo fmt --all -- --check
        displayName: Cargo Fmt
    - job: Lint
      steps:
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: rustup target add wasm32-unknown-unknown
        displayName: Install Rust WASM target
      - script: cargo clippy --all --target=wasm32-unknown-unknown -- -D warnings
        displayName: Cargo Clippy
  - stage: Release
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
    - job: Verify
      steps:
      - script: '[[ `cat CHANGELOG.md` == "## $(Build.SourceBranchName)"* ]]'
        displayName: Verify changelog was updated
      - script: '[[ `sed "3q;d" Cargo.toml` = "version = \"$(Build.SourceBranchName)"* ]]'
        displayName: Verify Cargo.toml was updated
    - job: GitHub
      dependsOn: Verify
      steps:
      - template: continuous-integration/install-binaryen.yaml
      - template: continuous-integration/install-wasmbindgen.yaml
      - template: continuous-integration/install-wasmpack.yaml
      - script: sudo npm install -g vsce
        displayName: Install dependencies (vsce)
      - script: BUILDSH_RELEASE=1 ./build.sh package
        displayName: Package extension
      - script: sed '/##/q' <(tail CHANGELOG.md -n +3) | head -n -2 > github-release-changelog-diff.md
        displayName: Prepare changelog
      - task: GitHubRelease@0
        displayName: Release
        inputs:
          gitHubConnection: github/pustaczek
          repositoryName: pustaczek/icie
          releaseNotesFile: github-release-changelog-diff.md
          assets: target/evscode/icie-*.vsix
          addChangeLog: false
